info:
  name: "John Doe"
  title: ""
  email: "john.doe@example.com"
  profile_picture: "./configs/default/assets/me.png"
  linkedin: "john-doe"
  github: "johndoe"
  malt: "johndoe"
  location: "New York, USA"
skills:
  Languages:
    items:
      - "Typescript"
      - "Golang"
  Databases:
    items:
      - "PostgreSQL"
      - "Redis"
      - "ClickHouse"

experiences:
  - company: "Tech Corp A"
    roles:
      - title: ""
        date: ""
        technologies:
          - "Golang"
          - "PostgreSQL"
          - "gRPC"

      - title: ""
        date: "2020 - 2022"
        technologies:
          - "ClickHouse"
          - "Kafka"
          - "Python"

  - company: "Tech Corp B"
    roles:
      - name: ""
        date: "2018 - 2020"
        tasks:
        technologies:
          - "Java"
          - "Elasticsearch"
          - "AWS Lambda"

