info:
  name: "John Doe"
  email: "johndoe@proton.me"
  profile_picture: "./configs/default/assets/me.png"
  linkedin: "https://www.linkedin.com/in/john-doe/"
  github: "https://github.com/johndoe"
  malt: "https://www.malt.fr/profile/johndoe"
  location: "Paris, France"
skills:
  Languages:
    items:
      - "Typescript"
      - "Golang"
  Databases:
    items:
      - "PostgreSQL"
      - "Redis"
      - "ClickHouse"
  Technologies:
    items:
      - "Kafka"
      - "gRPC"
  DevOps:
    items:
      - "Docker"
      - "Kubernetes"
      - "Bazel"
      - "Git"
      - "CI/CD"
      - "AWS"
      - "GCP"

experiences:
  - company: "Salesramp"
    roles:
      - title: ""
        date: ""
        items:
          - name: ""
        technologies:
          - "Go"
          - "PostgreSQL"
          - "ClickHouse"
          - "NodeJS"
          - "Typescript"
          - "Parse Server"

  - company: "Fastory.io"
    roles:
      - title: ""
        date: ""
        items:
          - name: ""
        technologies:
          - "Typescript"
          - "ReactJS"
          - "NextJS"
          - "HapiJS"
          - "AWS"
          - "Elasticsearch"
          - "PostgreSQL"

      - title: ""
        date: ""
        items:
          - name: ""
        technologies:
          - "Typescript"
          - "Javascript"
          - "Heroku"
          - "ReactJS"
          - "PostgreSQL"
          - "HapiJS"

education:
  - school: ""
    degree: ""
    date: "2013 - 2018"

