info:
  title: "Développeur Backend Freelance | Golang, TypeScript"

skills:
  Languages:
    label: "Langages"
  Databases:
    label: "Bases de données"
  Technologies:
    label: "Technologies"
  DevOps:
    label: "DevOps"

experiences:
  - company: "Tech Company"
    roles:
      - title: "Développeur Backend Golang - Freelance"
        date: "Avril 2024 - Février 2025"
        items:
          description: "Collaboration avec le CTO pour la création du produit."
          tasks:
            - "Architecture et implémentation de la base de données ClickHouse"
            - "Création d'un serveur Go gRPC pour la communication avec la base de données ClickHouse"
            - "Refactoring et optimisation de l'API"
            - "Migration de l'API vers TypeScript"
            - "Création de fonctions de communication gRPC entre les serveurs TypeScript et Go"
            - "Mise en place des bonnes pratiques"

  - company: "ATO"
    roles:
      - title: "Lead Développeur Full Stack"
        date: "Juin 2020 - Avril 2024"
        items:
          - description: "Lead développeur d'une équipe de 5-7 développeurs"
            tasks:
              - "Organisation des rituels"
              - "Priorisation des projets"
              - "Mentorat des développeurs juniors"
              - "Recrutement"
          - description: "Projet d'amélioration structurelle pour gérer l'augmentation du trafic"
            tasks:
              - "Migration en microservices"
              - "Mise en place de l'autoscaling"
              - "Migration de PostgreSQL vers Elasticsearch"
          - description: "Projet d'amélioration du code"
            tasks:
              - "Migration de Javascript vers Typescript"
              - "Création de composants React et NextJS"
          - description: "Ajouts de fonctionnalités"
            tasks:
              - "Création de multiples add-ons au sein de la plateforme ATO"
              - "Implémentation du système de connexion SAP/CDC en collaboration avec Tech Company"
      - title: "Développeur Full Stack"
        date: "Août 2019 - Mai 2020"
        items:
          - description: "Intégration dans une équipe de 4 développeurs"
            tasks:
              - "Migration d'une partie du serveur Javascript vers un serveur Next en Typescript"
              - "Implémentation de fonctionnalités"
              - "Correction de la dette technique"

education:
  - school: "Super école du numérique"
    degree: "Développeur Full Stack"

languages:
  - language: "Anglais"
    level: "Maîtrise professionnelle complète"
  - language: "Français"
    level: "Langue maternelle"
