name: Generate Resume PDF

on:
  push:
    branches:
      - main # Runs on push to main branch
  workflow_dispatch: # Allows manual execution

# Add permissions block
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Cache TeX Live packages
        uses: actions/cache@v4
        with:
          path: |
            /usr/share/texlive
            /usr/local/share/texlive
            ~/.texlive
          key: texlive-${{ runner.os }}-${{ hashFiles('src/*.md') }}
          restore-keys: |
            texlive-${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt install -y pandoc texlive-xetex

      - name: Convert Markdown to PDF (en)
        run: |
          make all

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Resume PDF
          path: output/

      - name: Commit PDF to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add output/
          git commit -m "Update generated resume PDF" || echo "No changes to commit"
          git push
